name: C/C++ CI

on: [push, pull_request]

jobs:
  linux-x64:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: build-linux-release-x64
        run: |
          git submodule update --init --recursive
          pip3 install --user scons
          scons platform=linux target=release bits=64 godot_cpp=yes generate_bindings=yes use_custom_api_file=yes custom_api_file=extension_api.ci.json -j $(nproc)
          ldd demo/addons/godot-git-plugin/linux/libgit_plugin.so
      - uses: actions/upload-artifact@v2
        with:
          name: libgit_plugin.linux.x86_64.release.dll-${{ github.sha }}
          if-no-files-found: error
          path: |
            demo/

  windows-x64:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"
      - uses: ilammy/msvc-dev-cmd@v1
      - name: build-windows-release-x64
        run: |
          git submodule update --init --recursive
          pip3 install --user scons
          scons platform=windows target=release bits=64 godot_cpp=yes generate_bindings=yes use_custom_api_file=yes custom_api_file=extension_api.ci.json -j $env:NUMBER_OF_PROCESSORS
          dumpbin /dependents .\demo\addons\godot-git-plugin\win64\libgit_plugin.dll
      - uses: actions/upload-artifact@v2
        with:
          name: libgit_plugin.windows.x86_64.release.dll-${{ github.sha }}
          if-no-files-found: error
          path: |
            demo/

  macos-x64:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: build-macos-release-x64
        run: |
          git submodule update --init --recursive
          brew install scons
          scons platform=osx target=release bits=64 godot_cpp=yes generate_bindings=yes use_custom_api_file=yes custom_api_file=extension_api.ci.json macos_arch=universal use_llvm=yes -j $(sysctl -n hw.logicalcpu)
          otool -L demo/addons/godot-git-plugin/osx/libgit_plugin.dylib
      - uses: actions/upload-artifact@v2
        with:
          name: libgit_plugin.osx.x86_64.release.dylib-${{ github.sha }}
          if-no-files-found: error
          path: |
            demo/
